global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_by: ['alertname', 'severity', 'category']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  
  routes:
    # Critical алерты сразу в телеграм
    - receiver: 'telegram'
      match:
        severity: critical
      group_wait: 10s
      repeat_interval: 1h
      
    # Warning алерты с задержкой
    - receiver: 'telegram'
      match:
        severity: warning
      group_wait: 30s
      repeat_interval: 4h

receivers:
  - name: 'telegram'
    webhook_configs:
      - url: 'http://alertmanager-telegram:8080'
        send_resolved: true

inhibit_rules:
  # Подавление warning если есть critical для того же хоста
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['instance']
  
  # Подавление ServiceDown если HostDown
  - source_match:
      alertname: 'HostDown'
    target_match:
      alertname: 'ServiceDown'
    equal: ['instance']
